### ISSUE TITLE
Doesn't generate an export file

### ISSUE THREAD

**Issue by msanity** [ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions#12]
I'm trying to use this and think I have everything setup correctly, but the script runs and I get no new files in my export folder. It doesn't throw any errors, but the Python window just closes.

**Comment by ChrisQGeorge** [comment]
Ok, does the window open and close right away when you run the app without showing any options, or does the file just not generate after going through the menus? If you did go through the terminal instructions, what options did you choose (In answering, I would avoid saying the account balance or account name)

**Comment by msanity** [comment]
So, the first time the Python terminal opens, it had an error about the "$" dollar sign being escaped, which I fixed by removing the "\" before it in the code. "main.py:28: SyntaxWarning: invalid escape sequence '\$'  runningBal = int(float(re.sub(",|\$","",input("What is the current account balance?: ")))*100)"

After that, the window opens and prompts for which file to import, so I choose my .csv. Then it asks what the current balance is, and I type in 4245.15. After I hit enter the Python window closes and no file is generated. 

I tried it with your test .csv and that one worked, so it must be something with my file, but I'm not sure what is tripping it up.

This is on Windows 10 running Python 3.12.

**Comment by ChrisQGeorge** [comment]
Ok, so I think I know what the problem could be. On a previous version of this script, there was an issue when parsing the CSV file where an unexpected character would cause the script to fail. I have since updated it to fix this issue, so I would recommend updating your version by doing the command "git pull" while in the directory if you downloaded it with git or just redownload the zip file. 
If you don't want to do that, you can also try deleting the content in the all the rows besides "Date", "Account", and "Amount". Do not delete the rows themselves though, just the content. It needs the CSV structure to work properly.

**Comment by ChrisQGeorge** [comment]
I am closing this for now due to inactivity, but if you are still having problems, please feel free to open another issue and we can go from there

**Comment by msanity** [comment]
OK, sorry for the slow response. I did some more tests this weekend and I think I figured out what is happening. 

It turns out when Excel saves CSV files, it makes some changes to the formatting, even if no other changes are made to the file. Example:

This is the raw CSV output from Mint:
![raw_Mint_CSV](https://github.com/ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions/assets/49246184/4dd388e4-d8ed-46f1-83ad-72a373bb266e)

This is the CSV after opened and saved in Excel:
![saved_Excel_CSV](https://github.com/ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions/assets/49246184/eee8e165-e888-463e-84c4-eb3eda71983f)

So Excel changes the Date formatting and removes a lot of the quotation marks. The raw files from Mint don't generate an export with your script, but the saved files from Excel do.

I also noticed on your **Test_Monarch_Transaction.csv** file (or any transaction CSV from Monarch), if I open that in Excel and save it, it changes the date formatting (YYYY-MM-DD to MM/DD/YYYY) and changes the hyphens to slashes. This also causes the script not to function properly.

Before saving in Excel:
![Code_11_13_23_09-49-12](https://github.com/ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions/assets/49246184/7d7b0ce3-a104-4030-9803-b3c76b5b8078)

After saving in Excel:
![Code_11_13_23_09-51-44](https://github.com/ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions/assets/49246184/f22e9b93-5027-4953-b3f5-404897550e5e)

Once I knew what the script is expecting for date formatting for both Mint trend balances (MMM-YY) and Monarch transactions (YYYY-MM-DD), I could make the update in Excel to the proper date formatting to get it to work properly. I'm not sure if I have some weird Excel setting turned on that is causing this, but it definitely screws with stuff. It's a pretty bog-standard install of Excel.

**Comment by ChrisQGeorge** [comment]
Yup, I got sooo frustrated with Excel changing the date format on me. I forgot what setting I changed but somehow I got it to stop happening. I made the script with the idea that it would look for the default date format directly from import, with Mint and Monarch so that people wouldn't have to open the file. If you just want to take a look at the imported file before using the script without making any changes, you should be able to just close without saving.
