### ISSUE TITLE
Enter negative balance for liability

### ISSUE THREAD

**Issue by mandrewbot3k** [ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions#13]
Just some feedback, when asked for a current balance on a credit line/card, you need to put the value in as negative, otherwise the balances will import improperly. Thanks for the script.

**Comment by ChrisQGeorge** [comment]
You're welcome! That's correct, it should be the actual account value (positive for asset negative for liability) rather than the absolute value. I decided to not distinguish between account types because there exist cases where an asset account could have a negative value (overdraft) or a liability account could have a positive balance (prepayment). 

I appreciate your feedback and I'll update the script and readme to make it clear what the intended account value should be.
